# Generated by Django 6.0.5 on 2026-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillsToShipColumns',
            fields=[
                ('column_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
