# Generated by Django 6.0.5 on 2026-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateAWB',
            fields=[
                ('awb_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Duplicate AWBs',
                'db_table': 'duplicate_awb',
            },
        ),
    ]
