# Generated by Django 6.0.5 on 2026-05-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waybillstoshipcolumns',
            options={'verbose_name_plural': 'Waybills To Ship Columns'},
        ),
        migrations.AlterModelTable(
            name='waybillstoshipcolumns',
            table='waybills_to_ship_columns',
        ),
    ]
