# Generated by Django 6.0.5 on 2026-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbdata',
            name='awb_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
