# Generated by Django 6.0.5 on 2026-05-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_awbdata_awb_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
