# Generated by Django 6.0.5 on 2026-05-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_waybillstoshipcolumns_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaybillsToShipColumns',
        ),
    ]
