# Generated by Django 6.0.5 on 2026-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0003_delete_waybillstoshipcolumns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWBData',
            fields=[
                ('awb_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('destination_iata', models.CharField(max_length=4)),
                ('consignee', models.CharField(max_length=255)),
                ('pieces', models.IntegerField()),
                ('weight', models.FloatField()),
                ('days_on_hand', models.IntegerField()),
                ('hours_remaining', models.IntegerField()),
                ('sent', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
