# Generated by Django 6.0.5 on 2026-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awbdata',
            old_name='pieces',
            new_name='pieces_on_hand',
        ),
        migrations.RenameField(
            model_name='awbdata',
            old_name='weight',
            new_name='weight_on_hand',
        ),
    ]
