# Generated by Django 6.0.5 on 2026-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_pieces_awbdata_pieces_on_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateAWB',
            fields=[
                ('awb_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
