# Generated by Django 6.0.5 on 2026-05-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_duplicateawb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awbdata',
            options={'verbose_name_plural': 'AWB Data'},
        ),
        migrations.AlterModelOptions(
            name='duplicateawb',
            options={'verbose_name_plural': 'Duplicate AWBs'},
        ),
        migrations.AlterModelTable(
            name='awbdata',
            table='awb_data',
        ),
        migrations.AlterModelTable(
            name='duplicateawb',
            table='duplicate_awb',
        ),
    ]
