# Generated by Django 6.0.5 on 2026-05-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowedEmails',
            new_name='AllowedEmail',
        ),
        migrations.AlterModelTable(
            name='allowedemail',
            table='allowed_email',
        ),
    ]
