# Generated by Django 6.0.5 on 2026-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freighters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('DASH100', 'Dash 100'), ('DASH300', 'Dash 300'), ('METRO', 'Metro'), ('OTHER', 'Other')], max_length=15)),
                ('tail_number', models.CharField(max_length=20)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELAYED', 'Delayed'), ('IN_MAINTENANCE', 'In Maintenance'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('ON_GROUND', 'On Ground')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('station_notified', models.BooleanField(default=False)),
                ('station_informed_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Freighters',
                'db_table': 'freighters',
            },
        ),
    ]
