# Generated by Django 6.0.5 on 2026-05-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freighters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freighters',
            options={'verbose_name_plural': 'Freighters'},
        ),
        migrations.AlterModelTable(
            name='freighters',
            table='freighters',
        ),
    ]
