# Generated by Django 6.0.5 on 2026-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awbstatus',
            name='image_url',
        ),
        migrations.AddField(
            model_name='awbstatus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='awb_images/'),
        ),
    ]
