# Generated by Django 6.0.5 on 2026-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_status', '0002_remove_awbstatus_image_url_awbstatus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbstatus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
