# Generated by Django 6.0.5 on 2026-05-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWBStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=50, unique=True)),
                ('destination_iata', models.CharField(max_length=10)),
                ('consignee', models.CharField(max_length=255)),
                ('pieces_on_hand', models.IntegerField(blank=True, null=True)),
                ('weight_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_on_hand', models.IntegerField(blank=True, null=True)),
                ('hours_remaining', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AWB Status',
                'db_table': 'awb_status',
            },
        ),
    ]
