# Generated by Django 6.0.5 on 2026-05-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('under_30', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AWBData',
            new_name='AWBUnder30Hours',
        ),
        migrations.AlterModelOptions(
            name='awbunder30hours',
            options={'verbose_name_plural': 'AWB Under 30 Hours'},
        ),
        migrations.AlterModelTable(
            name='awbunder30hours',
            table='awb_under_30_hours',
        ),
    ]
