# Generated by Django 6.0.5 on 2026-05-24 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('under_30', '0002_alter_awbstatus_awb_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awbstatus',
            name='sent',
        ),
    ]
