# Generated by Django 6.0.5 on 2026-05-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under_30', '0003_remove_awbstatus_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awbstatus',
            name='hours_remaining',
        ),
        migrations.AddField(
            model_name='awbstatus',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
