# Generated by Django 6.0.5 on 2026-05-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under_30', '0004_remove_awbstatus_hours_remaining_awbstatus_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
