# Generated by Django 6.0.5 on 2026-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWBScanner',
            fields=[
                ('awb_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('destination_iata', models.CharField(choices=[('YBT', 'YBT'), ('YCR', 'YCR'), ('YVZ', 'YVZ'), ('YGO', 'YGO'), ('ZGI', 'ZGI'), ('YIV', 'YIV'), ('XLB', 'XLB'), ('YYB', 'YYB'), ('YNO', 'YNO'), ('YNE', 'YNE'), ('YOH', 'YOH'), ('YPM', 'YPM'), ('YRL', 'YRL'), ('YRS', 'YRS'), ('ZPB', 'ZPB'), ('ZSJ', 'ZSJ'), ('YAM', 'YAM'), ('YXL', 'YXL'), ('YSB', 'YSB'), ('ZTM', 'ZTM'), ('XSI', 'XSI'), ('YST', 'YST'), ('XTL', 'XTL'), ('YTH', 'YTH'), ('YQT', 'YQT'), ('ZAC', 'ZAC'), ('ZRJ', 'ZRJ'), ('YWG', 'YWG')], max_length=10)),
                ('scan_count', models.IntegerField(default=0)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannerDestinations',
            fields=[
                ('destination', models.CharField(choices=[('YBT', 'YBT'), ('YCR', 'YCR'), ('YVZ', 'YVZ'), ('YGO', 'YGO'), ('ZGI', 'ZGI'), ('YIV', 'YIV'), ('XLB', 'XLB'), ('YYB', 'YYB'), ('YNO', 'YNO'), ('YNE', 'YNE'), ('YOH', 'YOH'), ('YPM', 'YPM'), ('YRL', 'YRL'), ('YRS', 'YRS'), ('ZPB', 'ZPB'), ('ZSJ', 'ZSJ'), ('YAM', 'YAM'), ('YXL', 'YXL'), ('YSB', 'YSB'), ('ZTM', 'ZTM'), ('XSI', 'XSI'), ('YST', 'YST'), ('XTL', 'XTL'), ('YTH', 'YTH'), ('YQT', 'YQT'), ('ZAC', 'ZAC'), ('ZRJ', 'ZRJ'), ('YWG', 'YWG')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
