# Generated by Django 6.0.5 on 2026-05-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awb_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awbscanner',
            options={'verbose_name_plural': 'AWB Scanners'},
        ),
        migrations.AlterModelOptions(
            name='scannerdestinations',
            options={'verbose_name_plural': 'Scanner Destinations'},
        ),
        migrations.AlterModelTable(
            name='awbscanner',
            table='awb_scanner',
        ),
        migrations.AlterModelTable(
            name='scannerdestinations',
            table='scanner_destinations',
        ),
    ]
