# Generated by Django 6.0.5 on 2026-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_scanner', '0003_delete_scannerdestinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbscanner',
            name='scan_time',
            field=models.DateTimeField(),
        ),
    ]
