# Generated by Django 6.0.5 on 2026-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_scanner', '0004_alter_awbscanner_scan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awbscanner',
            name='scan_time',
        ),
        migrations.AddField(
            model_name='awbscanner',
            name='full_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='awbscanner',
            name='destination_iata',
            field=models.CharField(choices=[('YGO', 'YGO'), ('YIV', 'YIV'), ('YOH', 'YOH'), ('YST', 'YST'), ('WGK', 'WGK')], max_length=10),
        ),
    ]
