# Generated by Django 6.0.5 on 2026-05-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_scanner', '0005_remove_awbscanner_scan_time_awbscanner_full_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbscanner',
            name='scan_count',
            field=models.IntegerField(default=1),
        ),
    ]
