# Generated by Django 6.0.5 on 2026-05-31 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb_scanner', '0006_alter_awbscanner_scan_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbscanner',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
