# Generated by Django 6.0.5 on 2026-05-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicateawb',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='days_on_hand',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='hours_remaining',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='pieces_on_hand',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='duplicateawb',
            name='weight_on_hand',
        ),
    ]
