# Generated by Django 6.0.5 on 2026-05-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplication', '0002_remove_duplicateawb_consignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicateawb',
            name='id',
        ),
        migrations.AlterField(
            model_name='duplicateawb',
            name='awb_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
